import './globals.css'
import { inter, vidaloka } from '../../Helper/font'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " " + vidaloka.className}>{children}</body>
    </html>
  )
}
